# Use Node 10
# React App #

FROM node:12-slim as build


# Creata a folder for our app

RUN mkdir /app


# Set up the working directory

WORKDIR /app


ENV PATH /app/node_modules/.bin:$PATH

# Copy our package.json file first, then run `npm install`.
# This is an optimization we can make, as this layer will be
# cached, meaning that if we don't change the package.json file,
# this step doesn't need to be performed again
COPY package.json .
COPY package-lock.json .

# Note that we're installing all dependencies, unlike 
# the buildpack

RUN npm install


# Copy the rest of the application

COPY . .


# Build the React application. It will output static files
# Into the /build folder

RUN npm run build


# --------------------

# Create a second-stage which copies the /build folder
# and uses http-server to host the application

# FROM node:10-slim

FROM nginx:1.17.8-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]