name: Deployment pipeline

on:
  push:
    branches:
      - master
      - development
      - developmentv2
      - postgres
      - prismav2
      - env-vars
      - eslint
      - base
      - server

jobs:
  build:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: '12'
      - name: backend, install, lint, build and test
        run: | 
          npm install
          npm run lint
          npm ci
          npm run build --if-present
          npm test
      - name: frontend, install, lint, build and test
        working-directory: "./client"
        run: | 
          npm install
          npm run lint
          npm ci
          npm run build --if-present
          npm test


  # frontend:    
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: '12'
  #     - name: frontend, install, lint, build and test
  #       working-directory: "./client"
  #       run: | 
  #         npm install
  #         npm run lint
  #         npm ci
  #         npm run build --if-present
  #         npm test


